import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
const errs = [];
page.on("pageerror", e => errs.push(e.message));
await page.goto("file:///home/user/nordschleife/index.html", { waitUntil: "load" });
await page.waitForTimeout(1500);
const n = await page.locator("#section-list li").count();
console.log("file:// sections:", n, "markers:", await page.locator(".sec-marker").count(), "errors:", errs.length ? errs : "none");
await browser.close();
process.exit(n === 41 && errs.length === 0 ? 0 : 1);
